install hub from apk repo

diff --git a/circle/functions b/circle/functions
--- a/circle/functions
+++ b/circle/functions
@@ -112,20 +112,24 @@ install_google_cloud_sdk() {
 
 install_hub() {
   if ! which hub >/dev/null ; then
+    if which apk >/dev/null; then
+      echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
+      apk add --no-cache hub
+    else
+      info "Downloading hub-linux-amd64-$HUB_VERSION.tgz..."
+      if ! curl -sSLO https://github.com/github/hub/releases/download/v$HUB_VERSION/hub-linux-amd64-$HUB_VERSION.tgz; then
+        error "Could not download hub..."
+        return 1
+      fi
 
-    info "Downloading hub-linux-amd64-$HUB_VERSION.tgz..."
-    if ! curl -sSLO https://github.com/github/hub/releases/download/v$HUB_VERSION/hub-linux-amd64-$HUB_VERSION.tgz; then
-      error "Could not download hub..."
-      return 1
+      info "Installing hub..."
+      if ! tar -zxf hub-linux-amd64-$HUB_VERSION.tgz --strip 2 hub-linux-amd64-$HUB_VERSION/bin/hub; then
+        error "Could not install hub..."
+        return 1
+      fi
+      chmod +x hub
+      mv hub /usr/local/bin/hub
     fi
-
-    info "Installing hub..."
-    if ! tar -zxf hub-linux-amd64-$HUB_VERSION.tgz --strip 2 hub-linux-amd64-$HUB_VERSION/bin/hub; then
-      error "Could not install hub..."
-      return 1
-    fi
-    chmod +x hub
-    mv hub /usr/local/bin/hub
 
     if ! hub version; then
       return 1
