Add function to update minideb-extras repo

diff --git a/circle/functions b/circle/functions
--- a/circle/functions
+++ b/circle/functions
@@ -389,14 +389,37 @@ git_configure() {
 
 git_create_branch() {
   git fetch development 2>/dev/null || return 1
-  if ! git checkout $1-$2 2>/dev/null; then
+  if ! git checkout $1 2>/dev/null; then
     info "Creating branch for new pull-request..."
-    git checkout -b $1-$2
+    git checkout -b $1
   else
     info "Amending updates to existing branch..."
     BRANCH_AMEND_COMMITS=1
   fi
   return 0
+}
+
+# This function expects two arguments: <repo to update> <branch name to merge>
+git_automerge_branch() {
+  REPO_TO_UPDATE=$1
+  BRANCH_NAME=$2
+  info "Auto-merging $BRANCH_NAME in $REPO_TO_UPDATE..."
+  git checkout master >/dev/null
+  git merge --no-ff $BRANCH_NAME >/dev/null
+  git remote remove origin >/dev/null
+  git remote add origin https://$GITHUB_USER@$(echo ${REPO_TO_UPDATE/https:\/\/}).git >/dev/null
+  git push origin master >/dev/null
+}
+
+# This function expects two arguments: <pattern to search> <pattern to exclude>
+git_cleanup_old_branches() {
+  info "Cleaning up old branches in development that match '$1' (excluding '$2')"
+  git fetch development >/dev/null
+  for branch in $(git branch --remote --list development/$1 | sed 's?.*development/??' | grep -v "$2")
+  do
+    log "Deleting $branch..."
+    git push development :$branch >/dev/null
+  done
 }
 
 dockerhub_update_description() {
@@ -564,7 +587,7 @@ update_chart_in_repo() {
   CHART_VERSION_FIRST_UPDATE="${CHART_VERSION%.*}.$((${CHART_VERSION##*.}+1))"
 
   # create a branch for the updates
-  git_create_branch $CHART_NAME $CHART_VERSION_FIRST_UPDATE
+  git_create_branch "${CHART_NAME}-${CHART_VERSION_FIRST_UPDATE}"
 
   # check if we should calculate next chart version from version in master or version in existing branch
   CHART_VERSION_IN_BRANCH=$(grep '^version:' $CHART_PATH/Chart.yaml | awk '{print $2}')
@@ -609,22 +632,12 @@ update_chart_in_repo() {
 
       # auto merge updates to https://github.com/bitnami/charts
       if [[ $REPO_TO_UPDATE == "https://github.com/bitnami/charts" ]]; then
-        info "Auto-merging $CHART_NAME-$CHART_VERSION_FIRST_UPDATE..."
-        git checkout master >/dev/null
-        git merge --no-ff $CHART_NAME-$CHART_VERSION_FIRST_UPDATE >/dev/null
-        git remote remove origin >/dev/null
-        git remote add origin https://$GITHUB_USER@$(echo ${REPO_TO_UPDATE/https:\/\/}).git >/dev/null
-        git push origin master >/dev/null
+        git_automerge_branch $REPO_TO_UPDATE "${CHART_NAME}-${CHART_VERSION_FIRST_UPDATE}"
       fi
     fi
 
     info "Cleaning up old branches..."
-    git fetch development >/dev/null
-    for branch in $(git branch --remote --list development/$CHART_NAME-* | sed 's?.*development/??' | grep -v "^$CHART_NAME-$CHART_VERSION_FIRST_UPDATE$")
-    do
-      log "Deleting $branch..."
-      git push development :$branch >/dev/null
-    done
+    git_cleanup_old_branches "${CHART_NAME}-*" "^$CHART_NAME-$CHART_VERSION_FIRST_UPDATE$"
   else
     warn "Chart release/updates skipped!"
   fi
@@ -641,4 +654,99 @@ update_chart_in_repo() {
   # Exiting from charts/ repository
   cd ..
   rm -rf charts
+}
+
+# Expects two parameters: <distro codename> and <docker image digest>
+update_minideb_extras() {
+    if [ -z "$1" ] || [ -z "$2" ]
+    then
+        error "Wrong arguments passed to update_minideb_extras function"
+        exit 1
+    fi
+
+    DIST=$1
+    DIST_BUILD_ID=$2
+    REPO_TO_UPDATE="https://github.com/bitnami/minideb-extras"
+    BASENAME=bitnami/minideb
+
+    echo "Cloning '$REPO_TO_UPDATE' repo..."
+    if ! git clone --quiet --single-branch $REPO_TO_UPDATE minideb-extras; then
+        error "Could not clone $REPO_TO_UPDATE..."
+        exit 1
+    fi
+    cd minideb-extras
+
+    # add development remote
+    git remote add development "https://$GITHUB_USER@github.com/$GITHUB_USER/$(echo ${REPO_TO_UPDATE/https:\/\/github.com\/bitnami\/} | tr / -).git"
+
+    # lookup the distro in minideb-extras
+    DIST_PATH=
+    for d in $(find * -type d -name $DIST )
+    do
+        if [ -f "$d/Dockerfile" ]; then
+            DIST_PATH=$d
+            break
+        fi
+    done
+
+    if [[ -z $DIST_PATH ]]; then
+        error "Distro '$DIST' could not be found in '$REPO_TO_UPDATE' repo"
+        continue
+    else
+        cd "$DIST_PATH"
+    fi
+
+    if [[ -z $GITHUB_USER || -z $GITHUB_PASSWORD ]]; then
+        error "GitHub credentials not configured. Aborting..."
+        exit 1
+    fi
+
+    git_configure
+
+    # Check if we need to update the Dockerfile
+    if grep "${DIST_BUILD_ID}" Dockerfile &>/dev/null ; then
+        echo "Dockerfile for dist ${DIST} is already using the new build"
+        continue
+    fi
+
+    # Create branch
+    BRANCH_NAME_BASE="minideb_update"
+    BRANCH_NAME="${BRANCH_NAME_BASE}_${DIST}_$(date +%Y%m%d_%H%M)"
+    if ! git_create_branch $BRANCH_NAME ; then error "Could not create new branch..."; exit 1; fi
+
+    # Substitute and bump image version
+    sed -i "s|^FROM .*$|FROM ${BASENAME}@${DIST_BUILD_ID}|" ./Dockerfile
+    # Bump image version
+    IMAGE_VERSION=$(grep '^ENV BITNAMI_IMAGE_VERSION' ./Dockerfile | awk -F '=' '{print $2}')
+    sed -i "s|^ENV BITNAMI_IMAGE_VERSION.*$|ENV BITNAMI_IMAGE_VERSION=${IMAGE_VERSION%r*}r$((${IMAGE_VERSION##*r}+1))|" ./Dockerfile
+
+    # Commit changes
+    git add ./Dockerfile
+    git commit -m "[$DIST] Update minideb base image" >/dev/null
+
+    # Push branch and create pull request
+    echo "Publishing branch to remote repo..."
+    git push development ${BRANCH_NAME} >/dev/null
+
+    install_hub || exit 1
+
+    echo "Creating pull request with '$REPO_TO_UPDATE' repo..."
+    if ! hub pull-request -m "[$DIST] Update minideb base image"; then
+        error "Could not create pull request"
+        exit 1
+    fi
+
+    # auto merge updates
+    # only enable when we are certain automatic PRs are correct
+    # echo "Auto-merging ${BRANCH_NAME}..."
+    # git_automerge_branch $REPO_TO_UPDATE $BRANCH_NAME
+
+    echo "Cleaning up old branches..."
+    git_cleanup_old_branches "${BRANCH_NAME_BASE}-*" "^${BRANCH_NAME}$"
+
+    info "Cleaning up repository"
+    # Exiting from 'minideb-extras' repository
+    cd ../../
+    info "Moving minideb-extras to minideb-extras-$DIST"
+    rm -rf minideb-extras
 }
